adj = input('Adjective: ')
noun = input('Noun: ')
noun1 = input('Noun: ')
adj1 = input('Adjective: ')
adj2 = input('Adjective: ')
noun2 = input('Noun: ')
adj3 = input('Adjective: ')
noun3 = input('Noun: ')
noun4 = input('Noun: ')
noun5 = input('Noun: ')
pluralNoun = input('Plural Noun: ')
pluralNoun1 = input('Plural Noun: ')
adj4 = input('Adjective: ')
noun6 = input('Noun: ')
noun7 = input('Noun: ')
noun8 = input('Noun: ')
adj5 = input('Adjective: ')
noun9 = input('Noun: ')
noun10 = input('Noun: ')
adj6 = input('Adjective: ')
noun11 = input('Noun: ')
adj7 = input('Adjective: ')
noun12 = input('Noun: ')
adj8 = input('Adjective: ')
noun13 = input('Noun: ')
noun14 = input('Noun: ')

madlibs = f"""
Once upon a time, in a land far, far away, there lived a(n) {adj} {noun}. This {noun1} was known for being very {adj1}. In fact, everyone in the kingdom called him/her the {adj2} {noun2}. One day, the {adj3} {noun3} decided to go on a journey to find the fabled {noun4} of {noun5}. Along the way, they encountered all sorts of {pluralNoun} and {pluralNoun1}. But the {adj4} {noun6} didn't let that stop them. They were determined to find the {noun7} of the {noun8}. Finally after many weeks of travelling, the {adj5} {noun9} came upon a(n) {noun10} that was guarded by a(n) {adj6} {noun11}. The {adj7} {noun12} didn't stand a chance against the {adj8} {noun13}'s {noun14} skills, and soon the treasure was theirs.
"""
print(madlibs)
